### ISSUE TITLE
ConsoleTest is flaky

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#1025]
Sometimes it fails like this:
```
app.cash.zipline.ConsoleTest[jvm] > logWithArguments[jvm] FAILED
    java.lang.AssertionError: expected:<INFO: this message for %s is a %d out of %d Jesse 8 10> but was:<null>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
```

**Comment by swankjesse** [comment]
Still flaky.

```

app.cash.zipline.ConsoleTest[jvm] > logWithArguments[jvm] FAILED
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 1m, the test coroutine is not completing
        at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:351)
        at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2$1.invoke(TestBuilders.kt:335)
        at app//kotlinx.coroutines.InternalCompletionHandler$UserSupplied.invoke(CompletionHandler.common.kt:67)
        at app//kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1438)
        at app//kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1483)
        at app//kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:806)
        at app//kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:766)
        at app//kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:682)
        at app//kotlinx.coroutines.JobSupport.cancelCoroutine(JobSupport.kt:669)
        at app//kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at app//kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:498)
        at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
        at app//kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
        at java.base@11.0.23/java.lang.Thread.run(Thread.java:829)
```

https://github.com/cashapp/zipline/actions/runs/9177320136/job/25234634822?pr=1318

**Comment by JakeWharton** [comment]
Still flaky.

```
ConsoleTest[jvm] > logWithArguments[jvm] FAILED
    kotlinx.coroutines.test.UncompletedCoroutinesError: After waiting for 1m, the test body did not run to completion
        at app//kotlinx.coroutines.test.TestBuildersKt__TestBuildersKt$runTest$2$1$2.invokeSuspend$lambda$0(TestBuilders.kt:354)
        at app//kotlinx.coroutines.InvokeOnCancelling.invoke(JobSupport.kt:1571)
        at app//kotlinx.coroutines.JobSupport.notifyCancelling(JobSupport.kt:1604)
        at app//kotlinx.coroutines.JobSupport.tryMakeCancelling(JobSupport.kt:826)
        at app//kotlinx.coroutines.JobSupport.makeCancelling(JobSupport.kt:786)
        at app//kotlinx.coroutines.JobSupport.cancelImpl$kotlinx_coroutines_core(JobSupport.kt:702)
        at app//kotlinx.coroutines.JobSupport.cancelCoroutine(JobSupport.kt:689)
        at app//kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
        at app//kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:505)
        at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:263)
        at app//kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:105)
        at java.base@11.0.25/java.lang.Thread.run(Thread.java:829)
```

https://github.com/cashapp/zipline/actions/runs/12400674565/job/34618931604
