### ISSUE TITLE
Crash: FileNotFoundException while attempting to fetch manifest from disk cache

### ISSUE THREAD

**Issue by rishabhvishwakarma-cred** [cashapp/zipline#1144]
We are using Zipline in our production app, and it's crashing for a few users with the below crash logs. 
I don't have exact steps to reproduce this. 

```
Fatal Exception: java.io.FileNotFoundException: No manifest file on disk with [fileName=2fe9fdcd3f473b842e84cf5b9cee079a37ea52c17ac773e29b5f6012de48a41d]
       at app.cash.zipline.loader.ZiplineCache.unpinManifest$zipline_loader_release(ZiplineCache.java:283)
       at app.cash.zipline.loader.internal.fetcher.FsCachingFetcher.unpin(FsCachingFetcher.java:58)
       at app.cash.zipline.loader.ZiplineLoader.loadFromNetwork(ZiplineLoader.kt:243)
       at app.cash.zipline.loader.ZiplineLoader.access$loadFromNetwork(ZiplineLoader.kt:57)
       at app.cash.zipline.loader.ZiplineLoader$loadFromNetwork$1.invokeSuspend(ZiplineLoader.kt:1057)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by rishabhvishwakarma-cred** [comment]
Fix: This issue was happening because we were using application cache dir for caching downloaded zipline files.
