### ISSUE TITLE
macosX64Test tests fail due to ‘KryoException: Buffer underflow.’ in Gradle

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#1170]
Here’s the failing part of a test run:
https://github.com/cashapp/zipline/actions/runs/6934933934/job/18864051443

```
* What went wrong:
Execution failed for task ':zipline-loader:macosX64Test'.
> Multiple build operations failed.
    Could not write XML test results for app.cash.zipline.loader.internal.cache.DatabaseCommonTest to file /Users/runner/work/zipline/zipline/zipline-loader/build/test-results/macosX64Test/TEST-app.cash.zipline.loader.internal.cache.DatabaseCommonTest.xml.
    Could not write XML test results for app.cash.zipline.loader.internal.cache.DatabaseNativeTest to file /Users/runner/work/zipline/zipline/zipline-loader/build/test-results/macosX64Test/TEST-app.cash.zipline.loader.internal.cache.DatabaseNativeTest.xml.
...
org.gradle.api.GradleException: Could not write XML test results for app.cash.zipline.loader.internal.cache.DatabaseCommonTest to file /Users/runner/work/zipline/zipline/zipline-loader/build/test-results/macosX64Test/TEST-app.cash.zipline.loader.internal.cache.DatabaseCommonTest.xml.
	at org.gradle.api.internal.tasks.testing.junit.result.Binary2JUnitXmlReportGenerator$JUnitXmlReportFileGenerator.run(Binary2JUnitXmlReportGenerator.java:125)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$QueueWorker.execute(DefaultBuildOperationExecutor.java:243)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runOperation(DefaultBuildOperationQueue.java:272)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.doRunBatch(DefaultBuildOperationQueue.java:253)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$0(DefaultBuildOperationQueue.java:238)
	at org.gradle.internal.resources.AbstractResourceLockRegistry.whileDisallowingLockChanges(AbstractResourceLockRegistry.java:50)
	at org.gradle.internal.work.DefaultWorkerLeaseService.whileDisallowingProjectLockChanges(DefaultWorkerLeaseService.java:236)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.lambda$runBatch$1(DefaultBuildOperationQueue.java:238)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:264)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:128)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.runBatch(DefaultBuildOperationQueue.java:224)
	at org.gradle.internal.operations.DefaultBuildOperationQueue$WorkerRunnable.run(DefaultBuildOperationQueue.java:192)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.AbstractManagedExecutor$1.run(AbstractManagedExecutor.java:47)
Caused by: com.esotericsoftware.kryo.KryoException: Buffer underflow.
	at com.esotericsoftware.kryo.io.Input.require(Input.java:181)
	at com.esotericsoftware.kryo.io.Input.readVarLong(Input.java:690)
	at com.esotericsoftware.kryo.io.Input.readLong(Input.java:685)
	at org.gradle.api.internal.tasks.testing.junit.result.TestOutputStore$Reader.<init>(TestOutputStore.java:254)
	at org.gradle.api.internal.tasks.testing.junit.result.TestOutputStore.reader(TestOutputStore.java:405)
	at org.gradle.api.internal.tasks.testing.junit.result.TestOutputStoreBackedResultsProvider.getReader(TestOutputStoreBackedResultsProvider.java:43)
	at org.gradle.api.internal.tasks.testing.junit.result.TestOutputStoreBackedResultsProvider.withReader(TestOutputStoreBackedResultsProvider.java:36)
	at org.gradle.api.internal.tasks.testing.junit.result.InMemoryTestResultsProvider.writeAllOutput(InMemoryTestResultsProvider.java:58)
	at org.gradle.api.internal.tasks.testing.junit.result.JUnitXmlResultWriter.writeOutputs(JUnitXmlResultWriter.java:94)
	at org.gradle.api.internal.tasks.testing.junit.result.JUnitXmlResultWriter.write(JUnitXmlResultWriter.java:79)
	at org.gradle.api.internal.tasks.testing.junit.result.Binary2JUnitXmlReportGenerator$JUnitXmlReportFileGenerator.run(Binary2JUnitXmlReportGenerator.java:122)
	... 17 more
```

I assume this JVM-side crash has a root cause in native code that sends test updates Kryo-encoded through a pipe. Perhaps that test is crashing in native code?

**Comment by JakeWharton** [comment]
This usually means the daemon disappeared. It probably needs more memory.
