### ISSUE TITLE
NoSuchElementException in ZiplineApis.rewritePair

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#1181]
This crash is triggered when the Zipline Gradle plugin is applied but there’s no Zipline classes on the classpath. We should just add those classes automatically so you can’t get it wrong.

```
java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at app.cash.zipline.kotlin.ZiplineApis.rewritePair(ZiplineApis.kt:298)
	at app.cash.zipline.kotlin.ZiplineApis.<init>(ZiplineApis.kt:196)
	at app.cash.zipline.kotlin.ZiplineIrGenerationExtension.generate(ZiplineIrGenerationExtension.kt:36)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr$lambda$1(JvmIrCodegenFactory.kt:225)
	at org.jetbrains.kotlin.psi2ir.Psi2IrTranslator.generateModuleFragment(Psi2IrTranslator.kt:107)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:255)
	at org.jetbrains.kotlin.backend.jvm.JvmIrCodegenFactory.convertToIr(JvmIrCodegenFactory.kt:59)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.convertToIr(KotlinToJVMBytecodeCompiler.kt:224)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:43)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:50)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
```

**Comment by TelephoneTan** [comment]
Please provide a workaround of this, I have both wasm target and jvm target in my gradle project, the wasm part can never be built just because I use zipline plugin in the project.
