### ISSUE TITLE
Unsupported OS: windows

### ISSUE THREAD

**Issue by TelephoneTan** [cashapp/zipline#1360]
I am trying to use zipline in win11 desktop target of KMP, but it failed with:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at app.cash.zipline.Zipline$Companion.create(Zipline.kt:198)
	at app.cash.zipline.loader.ZiplineLoader.loadFromManifest$zipline_loader(ZiplineLoader.kt:437)
	at app.cash.zipline.loader.ZiplineLoader.loadFromNetwork(ZiplineLoader.kt:305)
	at app.cash.zipline.loader.ZiplineLoader.access$loadFromNetwork(ZiplineLoader.kt:57)
	at app.cash.zipline.loader.ZiplineLoader$loadFromNetwork$1.invokeSuspend(ZiplineLoader.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:95)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:69)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:48)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at MainKt.main(main.kt:5)
	at MainKt.main(main.kt)
Caused by: java.lang.IllegalStateException: Unsupported OS: windows 11
	at app.cash.zipline.QuickJsNativeLoaderKt.loadNativeLibrary(QuickJsNativeLoader.kt:33)
	at app.cash.zipline.QuickJs.<clinit>(QuickJs.kt:36)
	... 15 more
```

**Comment by JakeWharton** [comment]
There is no Windows support at this time and we have no plans of adding it ourselves. See #1342 for more

If someone wants to fix it and send a PR I'd be happy to merge it.

**Comment by JakeWharton** [comment]
Now that we use Zig to build the native library, this should be easier to support.
