### ISSUE TITLE
Build Error: java.lang.NoSuchMethodError: void org.jetbrains.kotlin.ir.symbols.impl.IrSimpleFunctionSymbolImpl.<init>

### ISSUE THREAD

**Issue by Shabinder** [cashapp/zipline#1460]
Happens after updating to **kotlin 2.0.2x**

```
java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.ir.symbols.impl.IrSimpleFunctionSymbolImpl.<init>(org.jetbrains.kotlin.descriptors.FunctionDescriptor, int, kotlin.jvm.internal.DefaultConstructorMarker)'
	at app.cash.zipline.kotlin.IrKt.irConstructorBody(ir.kt:193)
	at app.cash.zipline.kotlin.IrKt.getOrCreateCompanion(ir.kt:409)
	at app.cash.zipline.kotlin.AdapterGenerator.generateAdapterIfAbsent(AdapterGenerator.kt:201)
	at app.cash.zipline.kotlin.AdapterGenerator.adapterExpression(AdapterGenerator.kt:94)
	at app.cash.zipline.kotlin.AddAdapterArgumentRewriter.rewrite(AddAdapterArgumentRewriter.kt:79)
	at app.cash.zipline.kotlin.ZiplineIrGenerationExtension$generate$transformer$1.visitCall(ZiplineIrGenerationExtension.kt:88)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:299)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitCall(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.expressions.IrCall.accept(IrCall.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrExpressionBody.transformChildren(IrExpressionBody.kt:31)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBody(IrElementTransformerVoid.kt:174)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpressionBody(IrElementTransformerVoid.kt:182)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpressionBody(IrElementTransformerVoid.kt:185)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitExpressionBody(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.expressions.IrExpressionBody.accept(IrExpressionBody.kt:21)
	at org.jetbrains.kotlin.ir.expressions.IrExpressionBody.transform(IrExpressionBody.kt:24)
	at org.jetbrains.kotlin.ir.declarations.IrField.transformChildren(IrField.kt:47)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitField(IrElementTransformerVoid.kt:96)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitFieldNew(IrElementTransformerVoidWithContext.kt:138)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitField(IrElementTransformerVoidWithContext.kt:76)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitField(IrElementTransformerVoid.kt:99)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitField(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.declarations.IrField.accept(IrField.kt:40)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:33)
	at org.jetbrains.kotlin.ir.declarations.IrProperty.transformChildren(IrProperty.kt:54)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitProperty(IrElementTransformerVoid.kt:116)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitPropertyNew(IrElementTransformerVoidWithContext.kt:134)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitProperty(IrElementTransformerVoidWithContext.kt:69)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitProperty(IrElementTransformerVoid.kt:119)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitProperty(IrElementTransformerVoid.kt:19)
	at org.jetbrains.kotlin.ir.declarations.IrProperty.accept(IrProperty.kt:45)
	at org.jetbrains.kotlin.ir.IrElementBase.transform(IrElementBase.kt:33)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.declarations.IrClass.transformChildren(IrClass.kt:82)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitDeclaration(IrElementTransformerVoid.kt:40)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitClass(IrElementTransformerVoid.kt:54)
	at org.jetbrains.kotlin.backend.common.IrElementTransformerVoidWithContext.visitClassNew(IrElementTransformerVoidWithContext.kt:126)
	at app.cash.zipline.kotlin.ZiplineIrGenerationExtension$generate$transformer$1.visitClassNew(ZiplineIrGenerationExtension.kt:43)
```

**Comment by JakeWharton** [comment]
With what version?

**Comment by Shabinder** [comment]
1.17.0, and I also tested building from **trunk** 
Zipline build is successful, but the project where I am using it, it fails with above.
