### ISSUE TITLE
Improve stacktrace quality

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#376]
Here’s a sample stacktrace:

```
2021-11-22 18:24:08.290 7634-7661/com.squareup.cash.sample E/Zipline: java.lang.Exception: TypeError: cannot read property 'fold_cq605b_k$' of null
        at <anonymous> (../../../../../CoroutineContext.kt:32)
        at withContext (../../../../../Builders.common.kt:151)
        at <anonymous> (../../../../../SnapshotState.kt:58872)
        at <anonymous> (../../../../../ziplineJs.kt:175)
        at <anonymous> (../../../../../<js-code>)
        at <anonymous> (../../../../../cash-zipline/samples/todo/src/jsMain/kotlin/app/cash/sample/todo/presentersJs.kt:114356)
        at <anonymous> (../../../../../Endpoint.kt:84)
        at <anonymous> (cash-todo.js)
        at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:77)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
```

### Function names are anonymous

I believe this is a limitation of QuickJS, which doesn’t assign functions the name of the variable they’re being assigned to. In particular, Chrome and Safari both print 'hello', but QuickJS does not:

```
var hello = function() { throw Error(); };
console.log(hello.name);
```

### File names don’t have path information

We’re getting file names like `../../../../../CoroutineContext.kt:32` but we want `kotlin/coroutines/CoroutineContext.kt`. I’m unsure where this information is lost.

**Comment by swankjesse** [comment]
https://github.com/bellard/quickjs/issues/93

**Comment by swankjesse** [comment]
No further action to take on this.
