### ISSUE TITLE
Gradle plugin isn’t configuring the Kotlin compiler plugin properly

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#377]
I’m in an Android app and I’m getting this:

```
    java.lang.IllegalStateException: unexpected call to Zipline.set: is the Zipline plugin configured?
        at app.cash.zipline.Zipline.set(Zipline.kt:121)
        at app.cash.cash4.DevelopmentTreehouse.loadCodeFromFlow(DevelopmentTreehouse.kt:92)
        at app.cash.cash4.DevelopmentTreehouse$loadRemoteCode$2.invokeSuspend(DevelopmentTreehouse.kt:81)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
```

I’m working around by adding a dependency:

```
  add("kotlinCompilerPluginClasspath", deps.zipline.kotlinPlugin)
```

**Comment by swankjesse** [comment]
No longer an issue.
