### ISSUE TITLE
Put the entry point into the manifest?

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#558]
Right now we’re doing this:

```
    val moduleId = "./my-module-name.zipline.js"
    val prepareFunction = "com.squareup.cash.prepareThing"
    zipline.evaluate("""require('$moduleId').$prepareFunction()""")
```

There’s only one correct value for moduleId and prepareFunction, and the manifest knows it.

If we get it wrong, things fail like so:

```
   Process: com.squareup.cash.beta.debug, PID: 11654
    app.cash.zipline.QuickJsException: "./my-module-name.zipline.js" not found in [...]
        at JavaScript.<anonymous>(define.js:11)
        at JavaScript.<eval>(?)
        at app.cash.zipline.QuickJs.evaluate(Native Method)
        at app.cash.zipline.QuickJs.evaluate(QuickJs.kt:110)
        at app.cash.zipline.QuickJs.evaluate$default(QuickJs.kt:109)
```

This is the equivalent of the `Main-Class` attribute in a JVM artifact’s manifest.

**Comment by swankjesse** [comment]
One gotcha – it’s possible the application layer wants to prepare the `Zipline` instance (by binding services, for example) before running this function.

**Comment by swankjesse** [comment]
This is done!
https://github.com/cashapp/zipline/pull/571
