### ISSUE TITLE
Support for overloaded functions

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#797]
I saw a crash without them:

```
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering
File being compiled: /data/app/kochiku-worker/shared/build-partition/squareup/cash-treehouse/treehouse/apis/flows/src/commonMain/kotlin/com/squareup/cash/treehouse/flows/FlowsApp.kt
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:47)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:239)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException$default(CodegenUtil.kt:235)
Caused by: java.lang.IllegalArgumentException: No argument for parameter VALUE_PARAMETER name:parameters index:2 type:@[Contextual] okio.ByteString?:
CALL 'public open fun getScreen (path: kotlin.String, navigator: com.squareup.cash.treehouse.navigation.Navigator, parameters: @[Contextual] okio.ByteString?): app.cash.redwood.treehouse.ZiplineTreehouseUi
```

**Comment by ean5533** [comment]
Example: https://github.com/squareup/cash-treehouse/pull/1394/commits/a73fdb71640dba891aeaa9afd2cc5b391c6049e8
