### ISSUE TITLE
Zipline incremental builds fail deserializing app.cash.zipline/Zipline.take

### ISSUE THREAD

**Issue by swankjesse** [cashapp/zipline#825]
I’ve seen incremental builds crash the compiler like this:

```
> Task :zipline:compileKotlinJs FAILED
e: Could not load module <app.cash.zipline:zipline> in an attempt to find deserializer for symbol app.cash.zipline/Zipline.take|-4455680448914447453[0].
e: org.jetbrains.kotlin.ir.linkage.KotlinIrLinkerInternalException: Kotlin IR Linker exception
        at org.jetbrains.kotlin.backend.common.serialization.linkerissues.KotlinIrLinkerIssue.raiseIssue(KotlinIrLinkerIssues.kt:26)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.resolveModuleDeserializer(KotlinIrLinker.kt:95)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.findDeserializedDeclarationForSymbol(KotlinIrLinker.kt:125)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.deserializeOrResolveDeclaration(KotlinIrLinker.kt:169)
        at org.jetbrains.kotlin.backend.common.serialization.KotlinIrLinker.getDeclaration(KotlinIrLinker.kt:158)
        at org.jetbrains.kotlin.backend.common.extensions.IrPluginContextImpl.resolveSymbolCollection(IrPluginContextImpl.kt:93)
        at org.jetbrains.kotlin.backend.common.extensions.IrPluginContextImpl.referenceFunctions(IrPluginContextImpl.kt:130)
        at app.cash.zipline.kotlin.ZiplineApis.rewritePair(ZiplineApis.kt:189)
        at app.cash.zipline.kotlin.ZiplineApis.<init>(ZiplineApis.kt:179)
        at app.cash.zipline.kotlin.ZiplineIrGenerationExtension.generate(ZiplineIrGenerationExtension.kt:35)
```

We should find a fix. A workaround is to do a `gradle clean`.

**Comment by swankjesse** [comment]
Obsolete.
