### ISSUE TITLE
'console' is not defined on v0.9.15

### ISSUE THREAD

**Issue by fluxxion82** [cashapp/zipline#875]
I'm playing with the Redwood emoji search and seeing an issue with zipline `0.9.15`. I'm running my development server and launching the android app but nothing shows on screen. I can see the app making successful requests to the server getting various `.zipline` files, but the zipline flow is returning `LoadResult.Failure ` with the following exception:

<details>
<summary>exception</summary>

```
app.cash.zipline.QuickJsException: 'console' is not defined
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at JavaScript.<anonymous>(jsMainSources/libraries/stdlib/js/src/kotlin/console.kt:78)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at JavaScript.<anonymous>(jsMainSources/libraries/stdlib/js/src/kotlin/console.kt:71)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at JavaScript.<anonymous>(jsMainSources/libraries/stdlib/js/src/kotlin/console.kt:10)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at JavaScript.<anonymous>(jsMainSources/libraries/stdlib/js/src/kotlin/console.kt:15)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at JavaScript.println(jsMainSources/libraries/stdlib/js/src/kotlin/console.kt:100)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at JavaScript.preparePresenters(presenter-treehouse/src/jsMain/kotlin/com/example/redwood/emojisearch/treehouse/presentersJs.kt:25)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at JavaScript.<eval>(RunApplication.kt)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at app.cash.zipline.QuickJs.execute(Native Method)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at app.cash.zipline.QuickJs.execute(QuickJs.kt:147)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at app.cash.zipline.QuickJs.evaluate(QuickJs.kt:111)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at app.cash.zipline.internal.QuickJsExtensionsKt.runApplication(quickJsExtensions.kt:44)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at app.cash.zipline.loader.ZiplineLoader.loadFromManifest$zipline_loader_debug(ZiplineLoader.kt:324)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at app.cash.zipline.loader.ZiplineLoader$loadFromManifest$1.invokeSuspend(Unknown Source:20)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
2023-01-31 23:34:15.359  3956-3994  System.err              com...emojisearch.android.composeui  W  	at java.lang.Thread.run(Thread.java:1012)
```
</details>

If I drop the zipline version to `0.9.14`, the emojiSearch app UI shows up.

Not sure it's helpful but the emoji search app code that I'm running is found here: https://github.com/fluxxion82/redwoodEmojiSeach , which I've basically copied from the redwood samples but replaced the redwood module dependencies with maven dependencies.

**Comment by fluxxion82** [comment]
oh I think i see why this is happening..i didn't really read the stack trace super close. my bad

**Comment by QuasiStellar** [comment]
> oh I think i see why this is happening..i didn't really read the stack trace super close. my bad

So what was the error? @fluxxion82
